# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-02 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saints',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='saints',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saints',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='saints',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='saints',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
