# Generated by Django 3.0.5 on 2020-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0003_auto_20200502_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saints',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
