# Generated by Django 3.0.5 on 2020-05-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0004_auto_20200502_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saints',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
